# Generated by Django 4.1.1 on 2022-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='payment',
            field=models.CharField(choices=[('Single Payment', 'Perpetual License'), ('Monthly Subscription', 'per Month'), ('Yearly Subscription', 'per Year')], max_length=200, verbose_name='Contenido'),
        ),
    ]
