# Generated by Django 4.1.1 on 2022-11-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.CharField(max_length=200, verbose_name='Calle y Numero')),
                ('colony', models.CharField(max_length=200, verbose_name='Colonia')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['price'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
