# Generated by Django 4.1.1 on 2022-11-04 21:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitle')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('url', models.URLField(verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('categories', models.ManyToManyField(related_name='get_portfolio_items', to='portfolio.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Portolio Item',
                'verbose_name_plural': 'Portolio Items',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='portfolio')),
                ('portfolioItem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolioitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PortolioItem',
        ),
    ]
