# Generated by Django 4.1.1 on 2022-11-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_portfolioitemimage_delete_portolioitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
    ]
