# Generated by Django 4.1.1 on 2022-11-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioitemimage_portfolioitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
    ]
